name = "fpvtoken"
compatibility_date = "2024-01-01"

[site]
bucket = "./out"
pages_build_output_dir = "./out"

[security]
ilas = false

[env.production]
name = "fpvtoken-production"
route = "fpvtoken.com/*"

[security]
ilas = false