name = "fpv-token-dapp"
compatibility_date = "2024-01-01"
main = true

[site]
bucket = ".vercel/output/static"
pages_build_output_dir = ".vercel/output/static"
production_branch = "main"

[security]
ilas = false

[env.production]
name = "fpvtoken"
routes = [
    { pattern = "fpvtoken.com", custom_domain = true }
]