
import './css/base.css';
import './css/navbar.css';
import './css/hero.css';
import './css/about.css';
import './css/airdrop.css';
import './css/tokenomics.css';
import './css/explorer.css';
import './css/here-we-go.css';
import './css/fpv-parts.css';
import './css/token-grid.css';
import './css/roadmap.css';
import './css/footer.css';
import './css/animations.css';
import './css/presale.css';
// ...add other CSS files as needed...
import { Inter } from "next/font/google";
import Providers from "./providers";
import "@rainbow-me/rainbowkit/styles.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
